title: FCS Programming Technology
email: ilya.blan4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/fcs-programming-technology" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
highlighter: rouge
theme: millidocs

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor
  - bin
  - CNAME
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE
  - docker-compose.yml
  - Makefile
  - script/cibuild

collections:
  pages:
    output: true
    permalink: /:collection/:title
